### ISSUE TITLE
Typo in the textbook

### ISSUE THREAD

**Issue by crvdgc** [blanchette/logical_verification_2023#3]
First off, thank you for the amazing book. I found a typo in Section 12.6. Summary of New Lean Constructs (Page 173 of 2023 Standard Edition, August 22, 2023). The last two lines of the Constant subsection:

|||
|---|---|
`Subtype.property` | function that extracts the base value from a subtype value
`Subtype.val` | function that extracts the property from a subtype value

The explanations should be flipped. Hope this helps.

**Comment by blanchette** [comment]
Thanks for the report. Fixed. Shall I name you in the preface? If so, what's your name?

**Comment by crvdgc** [comment]
No need. I'm just happy to help.
